[project]
name = "ecommerce-spider"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "parsel>=1.10.0",
    "playwright>=1.52.0",
]
