[project]
name = "ecommerce-spider"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "curl-cffi>=0.11.1",
    "parsel>=1.10.0",
    "playwright>=1.52.0",
    "rich>=14.0.0",
    "tldextract>=5.3.0",
]
